server:
    port: 8080

eureka:
    instance:
        hostname: localhost
        port: 9000
    client:
        serviceUrl: 
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
            - id: alunosModule
              uri: lb://ALUNOS
              predicates:
              - Path=/alunos/**
            - id: projetosModule
              uri: lb://PROJETOS
              predicates:
              - Path=/projetos/**