spring:
    application:
        name: alunos
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:db
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
server:
    port: 
        8081
eureka:
    instance:
        hostname: localhost
        port: 9000
    client:
        serviceUrl: 
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka